name: mdzen
channels:
  - conda-forge
dependencies:
  - python=3.11
  # --- conda-only or conda-preferred ---
  - ambertools>=24.0
  - smina
  - openmm>=8.3.1
  - pdbfixer>=1.9
  - rdkit>=2023.9.1
  - openblas
  # --- pip dependencies (delegated to pyproject.toml) ---
  - pip
  - pip:
    - -e .
